Repository Grow-In-CS/Study-With-Me, pull requests merged in 2025-08, with the labels that each got.

#34 7주차 컴퓨터구조
  0.스터디 내용 정리/진형/3. 컴퓨터 구조/1. 컴퓨터의 구성.md
  0.스터디 내용 정리/진형/3. 컴퓨터 구조/2. CPU 작동 원리.md
  0.스터디 내용 정리/진형/3. 컴퓨터 구조/3. 캐시 메모리.md
  0.스터디 내용 정리/진형/3. 컴퓨터 구조/4. 고정 소수점 & 부동 소수점.md
  0.스터디 내용 정리/진형/3. 컴퓨터 구조/5. 패리티 비트 & 해밍 코드.md
  0.스터디 내용 정리/진형/3. 컴퓨터 구조/ARM 프로시저.md
Labels: Look!! I studied

#36 [박현철] 7주차: 컴퓨터 구조
  0.스터디 내용 정리/현철/3. 컴퓨터 구조/1. 컴퓨터의 구성.md
  0.스터디 내용 정리/현철/3. 컴퓨터 구조/2. CPU 작동 원리.md
  0.스터디 내용 정리/현철/3. 컴퓨터 구조/3. 캐시 메모리.md
  0.스터디 내용 정리/현철/3. 컴퓨터 구조/4. 고정 소수점 & 부동 소수점.md
  0.스터디 내용 정리/현철/3. 컴퓨터 구조/5. 패리티 비트 & 해밍 코드.md
  0.스터디 내용 정리/현철/3. 컴퓨터 구조/6. ARM 프로시저.md
Labels: Look!! I studied

#37 6주차 스터디 완료 (IP주소, HTTP)
  2.네트워크/Readme.md
Labels: a presentation king

#38 7주차 스터디 완료 (컴퓨터 구조) 및 2장 모의면접
  2.네트워크/Readme.md
  2.네트워크/모의 면접/1. 지인 - 병민 - 진형.md
  3.컴퓨터 구조/Readme.md
Labels: a presentation king, a tense interview

#39 [곽병민] 8주차: 운영체제
  0.스터디 내용 정리/병민/4. 운영체제/1. 운영체제와 컴퓨터/1. 운영체제의 역할과 구조.md
  0.스터디 내용 정리/병민/4. 운영체제/1. 운영체제와 컴퓨터/2. 컴퓨터의 요소.md
  0.스터디 내용 정리/병민/4. 운영체제/2. 메모리/3. 메모리 계층.md
  0.스터디 내용 정리/병민/4. 운영체제/2. 메모리/4. 메모리 관리.md
Labels: Look!! I studied

#46 [이지인] 9주차: 프로세스와 스레드(1)
  0.스터디 내용 정리/지인/6. [Operating System]/image/pcb.png
  0.스터디 내용 정리/지인/6. [Operating System]/image/메모리구조.png
  0.스터디 내용 정리/지인/6. [Operating System]/image/컴파일.png
  0.스터디 내용 정리/지인/6. [Operating System]/image/포인터.png
  0.스터디 내용 정리/지인/6. [Operating System]/image/프로그램프로세스.png
  0.스터디 내용 정리/지인/6. [Operating System]/image/프로세스상태.png
  0.스터디 내용 정리/지인/6. [Operating System]/프로세스와 스레드/[Operating System] PCB.md
  0.스터디 내용 정리/지인/6. [Operating System]/프로세스와 스레드/[Operating System] 멀티프로세싱.md
  0.스터디 내용 정리/지인/6. [Operating System]/프로세스와 스레드/[Operating System] 프로세스 메모리 구조.md
  0.스터디 내용 정리/지인/6. [Operating System]/프로세스와 스레드/[Operating System] 프로세스와 컴파일 과정.md
  0.스터디 내용 정리/지인/6. [Operating System]/프로세스와 스레드/[Operating System] 프로세스의 상태.md
Labels: Look!! I studied

#48 [이지인] 10주차: 프로세스와 스레드(2), CPU 스케줄링 알고리즘
  0.스터디 내용 정리/지인/6. [Operating System]/CPU 스케줄링 알고리즘/[Operating System] CPU 스케줄링 알고리즘.md
  0.스터디 내용 정리/지인/6. [Operating System]/CPU 스케줄링 알고리즘/[Operating System] 선점형 비선점형.md
  0.스터디 내용 정리/지인/6. [Operating System]/image/mutex.png
  0.스터디 내용 정리/지인/6. [Operating System]/image/semaphore.png
  0.스터디 내용 정리/지인/6. [Operating System]/image/교착상태.png
  0.스터디 내용 정리/지인/6. [Operating System]/image/논블로킹.png
  0.스터디 내용 정리/지인/6. [Operating System]/image/동기비동기.png
  0.스터디 내용 정리/지인/6. [Operating System]/image/뮤텍스.png
  0.스터디 내용 정리/지인/6. [Operating System]/image/블로킹.png
  0.스터디 내용 정리/지인/6. [Operating System]/image/세마포어.png
  0.스터디 내용 정리/지인/6. [Operating System]/프로세스와 스레드/[Operating System] 경쟁 상태.md
  0.스터디 내용 정리/지인/6. [Operating System]/프로세스와 스레드/[Operating System] 공유자원과 임계영역.md
  0.스터디 내용 정리/지인/6. [Operating System]/프로세스와 스레드/[Operating System] 교착 상태.md
  0.스터디 내용 정리/지인/6. [Operating System]/프로세스와 스레드/[Operating System] 동기와 비동기.md
  0.스터디 내용 정리/지인/6. [Operating System]/프로세스와 스레드/[Operating System] 세마포어와 뮤텍스.md
Labels: Look!! I studied

#49 [곽병민] 10주차: 운영체제와 메모리 (프로세스와 스레드2, CPU 스케쥴링) 추가
  0.스터디 내용 정리/병민/4. 운영체제/3. 프로세스와 스레드/10. 스레드와 멀티스레딩.md
  0.스터디 내용 정리/병민/4. 운영체제/3. 프로세스와 스레드/11. 공유자원과 임계영역 - 세마포어,뮤텍스.md
  0.스터디 내용 정리/병민/4. 운영체제/3. 프로세스와 스레드/12. 교착상태.md
  0.스터디 내용 정리/병민/4. 운영체제/3. 프로세스와 스레드/13. 경쟁상태.md
  0.스터디 내용 정리/병민/4. 운영체제/3. 프로세스와 스레드/14. 동기와 비동기.md
  0.스터디 내용 정리/병민/4. 운영체제/4. CPU 스케쥴링 알고리즘/15. 비선점형 스케쥴링.md
  0.스터디 내용 정리/병민/4. 운영체제/4. CPU 스케쥴링 알고리즘/16. 선점형 스케쥴링.md
Labels: Look!! I studied

#51 9, 10주차 스터디 정리 완료 (운영체제)
  4.운영 체제/10. 공유자원과 임계영역/[Operating System] 공유자원과 임계영역.md
  4.운영 체제/11. 세마포어와 뮤텍스/[Operating System] 세마포어와 뮤텍스.md
  4.운영 체제/12. 교착상태/12. 교착상태.md
  4.운영 체제/13. 경쟁상태/13. 경쟁상태.md
  4.운영 체제/14. 동기와 비동기/14. 동기와 비동기.md
  4.운영 체제/15. 비선점형 스케쥴링/1. 비선점형 방식.md
  4.운영 체제/16. 선점형 스케쥴링/2. 선점형 방식.md
  4.운영 체제/5. 프로세스와 컴파일과정/4. 프로세스와 컴파일 과정.md
  4.운영 체제/6. 프로세스의 상태/프로세스의 상태.md
  4.운영 체제/7. 프로세스의 메모리 구조/[Operating System] 프로세스 메모리 구조.md
  4.운영 체제/8. PCB/8. PCB-컨텍스트 스위칭.md
  4.운영 체제/9. 멀티프로세싱/IPC.md
  4.운영 체제/Readme.md
Labels: a presentation king
